<?php 
    print($_POST['Numéro']);
    print($_POST['Type']);
    print($_POST['Baignoire']);
    print($_POST['Balcon']);
    print($_POST['MiniBar']);
    print($_POST['Télévision']);
    print($_POST['Vue']);
    print($_POST['Prix']);
    print($_POST['Nom']);
?>