<?php 
    print($_POST['Catégorie']);
    print($_POST['Pers']);
    print($_POST['MiniBar']);
    print($_POST['Télévision']);
    print($_POST['Baignoire']);
    print($_POST['Vue']);
    print($_POST['Balcon']);
?>